languages:
    - name: apl
    - name: bash
    - name: brainfuck
    - name: c
    - name: cpp
    - name: csharp
    - name: elixir
    - name: erlang
    - name: fsharp
    - name: go
    - name: haskell
    - name: idris
    - name: java
    - name: javascript
    - name: julia
    - name: lua
    - name: nim
    - name: ocaml
    - name: pascal
    - name: perl
    - name: php
    - name: prolog
    - name: python
    - name: r
    - name: racket
    - name: ruby
    - name: rust
    - name: typescript

defaultLanguage:
    memory: 256m
    cpus: 0.25
    timeout: 20
    concurrent: 10
    retries: 2
    outputLimit: 4k

buildConcurrently: true
prepareContainers: false
cleanupInterval: 30
port: 8081
