# Whether to build images concurrently.
# This will take up more resources when building all the images for the first time.
buildConcurrently: true

# Whether to start containers on startup of myriad.
prepareContainers: false

# Interval in minutes to kill all running languages containers.
cleanupInterval: 30

# Port to run myriad on.
port: 8081

# The default language configuration.
defaultLanguage:
    # The maximum memory and swap usage (separately) of a container.
    memory: 256m

    # The number of CPUs to use.
    cpus: 0.25

    # Time in seconds for an evaluation before the container kills itself.
    timeout: 20

    # The maximum number of concurrent evaluations in the container.
    concurrent: 5

    # The maximum number of retries when the evaluation fails due to a non-timeout related reason.
    retries: 10

    # The maximum number of bytes that can be outputted.
    outputLimit: 4k

# The languages to enable.
# The fields available are the same as in 'defaultLanguage', plus the name of the language.
# The names are as in your 'languages' folder.
languages:
    - name: apl
    - name: bash
    - name: brainfuck
    - name: c
    - name: cpp
    - name: csharp
    - name: elixir
    - name: erlang
    - name: fsharp
    - name: go
    - name: haskell
    - name: idris
    - name: java
    - name: javascript
    - name: julia
    - name: lua
    - name: nim
    - name: ocaml
    - name: pascal
    - name: perl
    - name: php
    - name: prolog
    - name: python
    - name: r
    - name: racket
    - name: ruby
    - name: rust
    - name: typescript
