name:                myriad
version:             0.1.0.0
github:              "1computer1/myriad"
license:             MIT
author:              "1Computer1"
maintainer:          "onecomputer00@gmail.com"
copyright:           "2019 1Computer1"

extra-source-files:
- README.md

synopsis:            Arbitrary code execution in Docker
category:            Server
description:         Please see the README

dependencies:
- aeson
- async
- base
- bytestring
- containers
- dhall
- lifted-base
- lifted-async
- monad-control
- monad-logger
- mtl
- optparse-applicative
- servant
- servant-server
- snowflake
- string-conversions
- text
- time
- transformers
- transformers-base
- typed-process
- wai
- warp

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies
- ViewPatterns

executable:
  main: Main.hs
  source-dirs: src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
